### ISSUE TITLE
Issue with launching the bot

### ISSUE THREAD

**Issue by bokerlol** [wizz13150/aiyabot#16]
**Describe the bug**  
When attempting to use launch.bat, I'm receiving the error below. I've made sure I have pycord installed and up to date as well. I even tried toying with the code a bit to see if I could 'fix' it, but didn't have much luck. I also made sure discord.py wasn't installed so there wouldn't be any conflicts. 

Considering you have been posting updates to this fork somewhat regularly, I figured it is something I'm doing wrong and wanted to see if you had any ideas because I'm at a loss. 

---

**Environment**
 - OS: Windows 11

---

**Console logs**  
Traceback (most recent call last):
  File "G:\Misc\aiyabot-main-wizz13150\aiya.py", line 6, in <module>
    from core import ctxmenuhandler
  File "G:\Misc\aiyabot-main-wizz13150\core\ctxmenuhandler.py", line 7, in <module>
    from core import settings
  File "G:\Misc\aiyabot-main-wizz13150\core\settings.py", line 14, in <module>
    self = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by bokerlol** [comment]
Worked properly on another PC so it is definitely something going wrong in my main PC. I will continue to debug and will open the issue again if I find anything that needs to be changed. Thanks.
